# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    advertisement_manager:
        class: Craigslist\MainBundle\Utility\AdvertisementManager
        arguments: ["@doctrine"]

    category_manager:
        class: Craigslist\MainBundle\Utility\CategoryManager
        arguments: ["@doctrine"]

    user_manager:
        class: Craigslist\MainBundle\Utility\UserManager
        arguments: ["@doctrine"]